### ISSUE TITLE
I find some errors?

### ISSUE THREAD

**Issue by BinWone** [codekansas/seqgan-text-tensorflow#3]
- in `utils.py` line 32, what is the format of the raw file? is one char a line? I think there is some problem in build the dictionary.

- in `utils.py` line 71, the yield should with shape (batch_size, seq_len), but the real result is with shape (seq_len, seq_len).

Please check !

**Comment by weizier** [comment]
@BinWone

**Comment by weizier** [comment]
@BinWone Line 32 is just all right there because set(f.read()) will tear out all chars in the string obtained by f.read().

However, line 71 I totally agree with you in which I think the right code is as follows:
`batch_idxs = np.random.choice(idxs, size=(batch_size,), replace=False)`
