### ISSUE TITLE
Error while running train.py

### ISSUE THREAD

**Issue by gregbatsi** [codekansas/seqgan-text-tensorflow#5]
AttributeError: 'module' object has no attribute 'simple_decoder_fn_train'

**Comment by ghost** [comment]
which version of tensorflow you are using?

**Comment by gregbatsi** [comment]
1.2.1

**Comment by gregbatsi** [comment]
I just downgrade to 1.0.0 and still having some issues. 
![screen shot 2017-07-23 at 18 52 21](https://user-images.githubusercontent.com/6041235/28500839-66feddae-6fd8-11e7-82ab-9901e86b2b4a.png)

**Comment by codekansas** [comment]
Looks like you're not running it using a GPU - use the `--only-cpu` command line flag.

**Comment by gregbatsi** [comment]
Still not working. There's must be an error because i get "InvalidArgumentError (see above for traceback): Incompatible shapes: [32,44,44] vs. [32,44,44,1]". The shapes are unequal. If I set the -n NUM_STEPS to 0 it is working. But the results are bizarre as you can see in the image.
![screen shot 2017-07-25 at 1 47 46 pm](https://user-images.githubusercontent.com/6041235/28568840-f5dfea3c-713f-11e7-8c26-e5134f1b9792.jpg)
